<?php
namespace Backend\Controllers\Sys;

use Backend\Controllers\BaseController;

/**
 * Class MenuController
 * @package Backend\Controllers\Sys
 * @RoutePrefix('/sys/menu')
 */
class MenuController extends BaseController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @Post(
     *     '/index'
     * )
     */
    public function indexAction()
    {
        echo __METHOD__;
    }
}