<?php
namespace Backend\Controllers\Sys;

use Backend\Controllers\BaseController;

/**
 * Class RoleController
 * @package Backend\Controllers\Sys
 * @RoutePrefix('/sys/role')
 */
class RoleController extends BaseController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @Post(
     *     '/index'
     * )
     */
    public function indexAction()
    {

    }
}
