<?php
namespace Backend\Controllers\Sys;

use Backend\Controllers\BaseController;

/**
 * Class RoleStaffMapController
 * @package Backend\Controllers\Sys
 * @RoutePrefix('/sys/roleStaffMap')
 */
class RoleStaffMapController extends BaseController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @Post(
     *     '/index'
     * )
     */
    public function indexAction()
    {
        echo __METHOD__;
    }

}