<?php
namespace Backend\Controllers\Sys;

use Backend\Controllers\BaseController;

/**
 * Class SysManageController
 * @package Backend\Controllers\Sys
 * @RoutePrefix('/sys/sysManage')
 */
class SysManageController extends BaseController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @Post(
     *     '/index'
     *     )
     */
    public function indexAction()
    {
    }

    /**
     * @Route(
     *     '/edit',
     *     methods = {'POST'}
     * )
     */
    public function editAction()
    {
        $data = $this->request->getPostedData('post');
        if(!$data['name']||!$data[''])
    }

}